# Generated by Django 3.0.8 on 2020-07-23 14:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=255)),
                ('Email_Id', models.EmailField(max_length=50)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('last_active', models.DateField()),
                ('user_type', models.CharField(max_length=5)),
                ('email_verified', models.BooleanField()),
                ('phone_verified', models.BooleanField()),
                ('Buggy_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('ShopId', models.IntegerField(primary_key=True, serialize=False)),
                ('Shop_name', models.CharField(max_length=30)),
                ('Shop_image', models.ImageField(upload_to=None)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buggiapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Address_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('Contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Secondary_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buggiapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Address_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('Contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Secondary_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ShopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buggiapp.Shop')),
            ],
        ),
    ]
